# 根据当前的环境修改gcc和cuda的版本
CXX                         :=  g++
CUDA_VER                    :=  12.1

# opencv和TensorRT的安装目录
TENSORRT_INSTALL_DIR        :=  /home/stoair/
OPENCV_INSTALL_DIR          :=  /usr/local/include/opencv4
# 大家根据自己的机器的型号选择一下ARCH，这个是nvcc需要用到的参数
ARCH= -gencode arch=compute_89,code=[sm_89,compute_89]

# Compile options
DEBUG                       :=  0
SHOW_WARNING                :=  0

# Compile applications
APP				                  :=  trt-infer
